config/routes.rb
HappyClients::Application.routes.draw do
  root "stories#index"
  resources :stories
  get "random" => "stories#random"
  get "archive" => "stories#archive"
  get "test" => "stories#test"
end

app/models/story.rb
class Story < ActiveRecord::Base
  scope :from_this_month, where("created_at > ? AND < ?", Time.now.beginning_of_month, Time.now.end_of_month)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

  caches_action :random

  def index
    @stories = Story.find( :all, :from_this_month, :order => "created_at DESC")
  end

  def show
    @story = Story.find(params[:id])
  end
  
  def edit
    @story = Story.find(params[:id])
  end
  
  def update
    @story = Story.find(params[:id])
    @story.update(story_params)
    redirect_to @story
  end

  def new
    @story = Story.new
  end
  
  def create
    @story = Story.new(story_params)
    @story.save
    redirect_to @story
  end

  def destroy
    @story = Story.find(params[:id])
    @story.destroy
    redirect_to @story
  end

  def random
    @story = Story.order("RANDOM()").find(:all, :from_this_month).first
  end

  def archive
  @stories = Story.find(:all).group_by { |story| story.created_at.strftime("%B") }
  end

private

  def story_params
    params[:story].permit(:company_name, :description, :rep_name, :vas_object, :case_link, :website, :quote)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav(link_text, link_path)
    class_name = current_page?(link_path) ? 'active' : ''

    content_tag(:li, :class => class_name) do
      link_to link_text, link_path
    end
  end
end

app/helpers/stories_helper.rb
module StoriesHelper
  def format_case_link(story)
    if story != nil
      link_to story.case_link, story.case_link, :target => '_blank'
    else
      'I was too lazy to add the case link.'
    end
  end

  def format_case_link_home(story)
    if story.case_link == 'http://' || story.case_link.blank?
      'I was too lazy to add the case link.'
    else
      link_to story.case_link, story.case_link, :target => '_blank'
    end
  end

  def format_website_link(story)
    if story != nil
      link_to story.website, story.website, :target => '_blank'
    else
      'I was too lazy to add the website url.'
    end
  end

  def format_website_link_home(story)
    if story.website == 'http://' || story.website.blank?
      'I was too lazy to add the website url.'
    else
      link_to story.website, story.website, :target => '_blank'
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HappyClients</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="/assets/stylesheets/narrow.css">

</head>
<body>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/stories/_footer.html.erb
<div class="footer">
  <p>Copyright &copy; <%= Date.today.year %><br>
    AppFolio | <strong>Will Sizoo</strong></p>
</div>

app/views/stories/_form.html.erb
<div class="form-group">
  <%= form_for(@story) do |f| %>
      <p>
        <%= f.label :company_name %><br/>
        <%= f.text_field :company_name, autofocus: true,:size => 50 %>
      </p>

      <p>
        <%= f.label :quote %><br/>
        <%= f.text_area :quote, cols: 100, rows: 7 %>
      </p>

      <p>
        <%= f.label :description %><br/>
        <%= f.text_area :description, cols: 100, rows: 7 %>
      </p>

      <p>
        <%= f.label :rep_name %><br/>
        <%= f.text_field :rep_name %>
      </p>

      <p>
        <%= f.label :vas_object %><br/>
        <%= f.text_field :vas_object %>
      </p>

      <p>
        <%= f.label :case_link %><br/>
        <% if @story.case_link == nil %>
            <%= f.text_area :case_link, :value => "http://", cols: 50 %>
        <% else %>
            <%= f.text_area :case_link, cols: 50 %>
        <% end %>
      </p>

      <p>
        <%= f.label :website %><br/>
        <% if @story.case_link == nil %>
            <%= f.text_area :website, :value => "http://", cols: 50 %>
        <% else %>
            <%= f.text_area :website, cols: 50 %>
        <% end %>

      </p>

      <p>
        <%= f.submit %> |
        <%= link_to 'Cancel', stories_path %>
      </p>
  <% end %>
</div>

app/views/stories/_header.html.erb
<div class="container">
  <div class="header">
    <ul class="nav nav-pills pull-right">

      <%= nav raw("<span class='glyphicon glyphicon' style='top:-1px'></span> All Stories"), stories_path %>
      <%= nav "Archive", archive_path %>
      <%= nav raw("<span class='glyphicon glyphicon-plus' style='top:-1px'></span> Add New Story"), new_story_path %>
      <%#= nav "Random Story", "/random" %>
    </ul>
  </div>
</div>

app/views/stories/_monthly_winner.html.erb
<% if Time.now >= "2014-10-07 16:03:00 -0700" %>

<%= link_to "Reveal the " + Date::MONTHNAMES[Date.today.month-1] + " Winner!", "/random", :class => 'btn btn-lg btn-primary' %>

<% end %>

app/views/stories/_random.html.erb
<article>
  <%# cache(:story) do %>
  <% if @story %>
  <div class="story">
    <% else %>
    <div class="story">
      <% end %>
      <header>
        <h3><%= link_to @story.company_name, @story %></h3>
      </header>

      <p><strong>Quote:</strong> <%= @story.quote %></p>

      <p><strong>Description:</strong> <%= truncate(@story.description, length: 40, separator: ' ') %> <%= link_to 'Show More', @story %></p>

      <p><strong>Rep Name:</strong> <%= @story.rep_name %></p>

      <p><strong>VAS Object:</strong> <%= @story.vas_object %></p>

      <p><strong>Case Link:</strong> <%= format_case_link_home(@story) %></p>

      <p><strong>Website:</strong> <%= format_website_link_home(@story) %></p>
    </div>
  <%# end %>
</article>

app/views/stories/_story.html.erb
<% @stories.each do |story| %>
    <div class="story<%= cycle('-grey', '') %>">
      <header>
        <h3><%= link_to story.company_name, story %></h3>
      </header>

      <p><strong>Quote:</strong> <%= story.quote %></p>

      <% if story.description.blank? %>
      <% else %>
          <p><strong>Description:</strong> <%= truncate(story.description, length: 40, separator: ' ') %> <%= link_to 'Show More', story %></p>
      <% end %>

      <p><strong>Rep Name:</strong> <%= story.rep_name %></p>

      <p><strong>VAS Object:</strong> <%= story.vas_object %></p>

      <p><strong>Case Link:</strong> <%= format_case_link_home(story) %></p>

      <p><strong>Website:</strong> <%= format_website_link_home(story) %></p>
    </div>

<% end %>

app/views/stories/archive.html.erb
<h1>Story Archive</h1>

<%= render 'header' %>

<!-- Split button -->
<div class="btn-group">
  <button type="button" class="btn btn-primary"><%= Date::MONTHNAMES[Date.today.month] %></button>
  <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
    <span class="caret"></span>
    <span class="sr-only">Toggle Dropdown</span>
  </button>
  <ul class="dropdown-menu" role="menu">
  <% @stories.each do |monthname| %>
      <li><a href="#<%= monthname.first %>"><%= monthname.first %></a></li>
      <li class="divider"></li>
  <% end %>
  </ul>

</div>

<% @stories.each do |monthname, stories| %>
    <h1 class="month"><div id="<%= monthname %>"></div><%= monthname %></h1>

      <% stories.each do |story| %>
          <div class="story<%= cycle('-grey', '') %>">
            <header>
              <h3><%= link_to story.company_name, story %></h3>
            </header>

            <p><strong>Quote:</strong> <%= story.quote %></p>

            <% if story.description.blank? %>
            <% else %>
                <p><strong>Description:</strong> <%= truncate(story.description, length: 40, separator: ' ') %> <%= link_to 'Show More', story %></p>
            <% end %>

            <p><strong>Rep Name:</strong> <%= story.rep_name %></p>

            <p><strong>VAS Object:</strong> <%= story.vas_object %></p>

            <p><strong>Case Link:</strong> <%= format_case_link_home(story) %></p>

            <p><strong>Website:</strong> <%= format_website_link_home(story) %></p>
          </div>
      <% end %>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing Happy Story: <%= @story.company_name + ' - ' + @story.rep_name %></h1>

<%= render 'header' %>

<%= render 'form' %>

<%= link_to "Delete", story_path(@story), method: :delete, data: {confirm: 'Are you sure you want to delete ' + @story.company_name + ' | ' + @story.vas_object + '?'}%>

<%= render 'footer' %>

app/views/stories/index.html.erb
<h1 style="font-size: 63px;">Happy Stories</h1>
<h3 style="margin-top: -11px; margin-left: 145px;">AppFolio Website Team</h3>


<%= render 'header' %>

<%= render 'monthly_winner' %>


<h2><%= pluralize(@stories.size, 'Happy Client') %> in <%= Date::MONTHNAMES[Date.today.month] %></h2>

<%= render 'story' %>

<br>
<%= render 'footer' %>

app/views/stories/new.html.erb
<h1>Add New Happy Client Story</h1>

<%= render 'header' %>


<%= render 'form' %>

<br>

<%= render 'footer' %>

app/views/stories/random.html.erb
<h1><%= Date::MONTHNAMES[Date.today.month-1] %> Winner</h1>

<%= render 'header' %>

<%= render 'random' %>

<br>

<%= link_to 'Refresh Random Story', url_for(params) %>

<br><br>

<%= render 'footer' %>

app/views/stories/show.html.erb
<h1>Happy Story</h1>
<%= render 'header' %>
<article>
  <header>
    <h2><%= @story.company_name %></h2>
  </header>
  <h3>Quote</h3>
  <p>
    <%= @story.quote %>
  </p>
  <h3>Description</h3>
  <p>
    <%= @story.description %>
  </p>
  <h3>Rep Name</h3>
  <p>
    <%= @story.rep_name %>
  </p>
  <h3>VAS Object</h3>
  <p>
    <%= @story.vas_object %>
  </p>
  <h3>Case Link</h3>
  <p>
    <%= format_case_link(@story) %>
  </p>
  <h3>Website</h3>
  <p>
    <%= format_website_link(@story) %>
  </p>
</article>

<br>

  <nav>
    <%= link_to "Back to All Stories", stories_path, :class => 'button' %>
    <%#= link_to "Edit", edit_story_path(@story) %>
    <%#= link_to "Delete", story_path(@story), method: :delete, data: {confirm: 'Are you sure you want to delete ' + @story.company_name + ' | ' + @story.vas_object + '?'}%>
  </nav>


<%= render 'footer' %>